faucet:
  build: ./
  restart: always
  ports:
    - "9000"
  environment:
    RPC_NODE: "https://ropsten.infura.io"
    VIRTUAL_PORT: "9000"
    VIRTUAL_HOST: "faucet.metamask.io,ropsten-faucet.metamask.io"
    LETSENCRYPT_HOST: "faucet.metamask.io,ropsten-faucet.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"