rpcProxy:
  image: kumavis/eth-rpc-whitelist-proxy
  restart: always
  environment:
    VIRTUAL_HOST: "rpc.metamask.io"
    VIRTUAL_PORT: "9000"
    PORT: "9000"
    RPC_NODE: "ethNode:9000"
  ports:
    - "9000"
  links:
    - ethNode

ethNode:
  image: ethereum/client-go
  restart: always
  command: "--rpc --rpcaddr '0.0.0.0' --rpcport '9000' "
  volumes:
    - /var/data/geth:/root/.ethereum
  ports:
    - "9000"